version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        UID: $UID
        GID: $GID
    ports:
      - "4000:4000"
    volumes:
      - ./src:/src
    tty: true
